apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: yw8nj6nvx-nodejs 
  janus-idp.io/tekton: yw8nj6nvx-nodejs
  backstage.io/kubernetes-id: yw8nj6nvx-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: yw8nj6nvx-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml