apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: yw8nj6nvx-nodejs
  janus-idp.io/tekton: yw8nj6nvx-nodejs
  backstage.io/kubernetes-id: yw8nj6nvx-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: yw8nj6nvx-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
