apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: yw8nj6nvx-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: yw8nj6nvx-nodejs 
  name: yw8nj6nvx-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: yw8nj6nvx-nodejs 
